version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - automated

  - package-ecosystem: gomod
    directory: /go
    schedule:
      interval: weekly
    labels:
      - dependencies
      - automated
