name: Lint

on:
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      openapi: ${{ steps.changes.outputs.openapi }}
      yamls: ${{ steps.changes.outputs.yamls }}
      workflows: ${{ steps.changes.outputs.workflows }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            openapi:
              - openapi.yaml
            yamls:
              - "**/*.y*ml"
            workflows:
              - ".github/workflows/*.y*ml"

  lint-openapi:
    needs: changes
    if: needs.changes.outputs.openapi == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Lint OpenAPI spec
        run: make lint-openapi

  lint-workflows:
    needs: changes
    if: needs.changes.outputs.workflows == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
      - name: Lint GitHub Actions workflows
        run: make lint-workflows

  lint-yamls:
    needs: changes
    if: needs.changes.outputs.yamls == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run yamllint
        shell: bash
        run: |
          make lint-yamls
